services:

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  
  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=nfl_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password1
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./initial-data.sql:/initial-data.sql
    
  airflow-webserver:
    image: apache/airflow:2.10.0
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    user: "50000:0"

  airflow-scheduler:
    image: apache/airflow:2.10.0
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    user: "50000:0"

  airflow-init:
    image: apache/airflow:2.10.0
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R 50000:0 /sources
        chmod -R 755 /sources
        airflow db migrate
        airflow users create \
          --username charlie \
          --firstname charlie \
          --lastname martell \
          --role Admin \
          --email admin@example.com \
          --password password
        exec /entrypoint airflow version
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqldb://root:password@database:3306/airflowMetadata
    user: "0:0"
    volumes:
      - ./sources:/sources

volumes:
  mysql-data: